name: ðŸš€ Generate Data

on:
  push:
    branches: ["master"] # runs on push to master
  schedule:
    - cron: "0 0 * * *" # runs every day

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all commits!
      - uses: actions/setup-python@v5
        with: 
            python-version: '3.11'
      - run: pip install cwltool

      - run: cwltool --quiet workflows/pipeline/pipeline.cwl --token ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: |
            Updated Metrics data